theme: osuny
params:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
          summary:
            active: true
            truncate: 0
  search:
    active: true
    positions:
      - upper-menu
  summary:
    position: content
  toc:
    force_offcanvas: true
  exhibitions:
    date_format: "01.02"
  events:
    date_format: "01.02"
  posts:
    single:
      options:
        signature: true
  persons:
    single:
      taxonomies:
        position: content
  components:
    lightbox:
      disabled: true
  image_sizes:
    _default:
      hero:
        desktop:  1920
      image:
        mobile:   480x850
        tablet:   768x1360
        desktop:  1920x1920
    blocks:
      chapter:
        desktop:  888
      image:
        desktop:  2600x2600
    sections:
      categories:
        hero:
          desktop:  1920
        hero_term:
          desktop:  1920
      diplomas:
        hero:
          desktop:  1920
        hero_single:
          desktop:  1920
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1920
      events:
        hero:
          desktop:  1920
        hero_single:
          desktop:  1920
        item:
          desktop:  1920
        layouts:
          list:
            desktop:  429
      organizations:
        hero:
          desktop:  1920
      pages:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1920
        item:
          tablet:   990
          desktop:  990
        layouts:
          list:
            desktop: 742
      papers:
        hero:
          desktop:  1920
      posts:
        hero:
          desktop:  1920
        hero_single:
          desktop:  1920
      projects:
        hero:
          desktop:  1920
        hero_single:
          desktop:  1920
      programs:
        hero:
          desktop:  1920
      publications:
        hero:
          desktop:  1920
      locations:
        hero:
          desktop:  1920
        hero_single:
          desktop:  1920
      persons:
        layouts:
          grid:
            desktop:  400